name: Outdated package checks

# Run workflow on pull request to the main branch
on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches: [ master, main, staging ]
    paths:
      - '.github/workflows/outdated.yml'
      - 'src/**'
      - 'tests/**'
      - 'package.json'
      - 'tailwind.config.js'
  
  workflow_dispatch:

jobs:
  outdated-packages-check:
    runs-on: ubuntu-slim

    name: Check outdated packages (${{ matrix.name }})

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: project root
            directory: '.'
          - name: playwright tests
            directory: 'tests/playwright'

    steps:
      - name: Check for outdated npm packages in ${{ matrix.name }}
        uses: trossr32/outdated-packages-action@7bb99b271f8a7fe64f7ea4be5ae297c5f2f118be
        with:
          use-npm-outdated: true
          npm-project-directory: ${{ matrix.directory }}
